steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/travels-289715/health-connect:$COMMIT_SHA", '.']
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/travels-289715/health-connect:$COMMIT_SHA"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'health-connect', '--image', 'gcr.io/travels-289715/health-connect:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--port', '8080']
images:
  - gcr.io/travels-289715/health-connect:$COMMIT_SHA